/* (Beta) Export of data model FishContainment of the subject dataModel.Aquaculture for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE FishContainment_type AS ENUM ('FishContainment');
CREATE TABLE FishContainment (
  address JSON,
  alternateName TEXT,
  areaServed TEXT,
  category TEXT,
  conductivity NUMERIC,
  dataProvider TEXT,
  dateCreated TIMESTAMP,
  dateModified TIMESTAMP,
  depth NUMERIC,
  description TEXT,
  dissolvedOxygen NUMERIC,
  feedingOperation TEXT,
  fishDensity JSON,
  fishDirection TEXT,
  fishSpeed NUMERIC,
  id TEXT PRIMARY KEY,
  location JSON,
  marineCurrents TEXT,
  name TEXT,
  observation TEXT,
  owner JSON,
  pH NUMERIC,
  redoxPotential NUMERIC,
  refFarm JSON,
  refSump JSON,
  salinity NUMERIC,
  seeAlso JSON,
  source TEXT,
  startedAt TIMESTAMP,
  temperature JSON,
  threats TEXT,
  totalDissolvedSolids NUMERIC,
  turbidity NUMERIC,
  type FishContainment_type,
  videoStream TEXT
);